// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCeam7VItri3p4laOVqT0_LtoOFhz7W4',
    appId: '1:705600051401:web:a026dfa7a6d64122e1d518',
    messagingSenderId: '705600051401',
    projectId: 'petcare-plus-bcck2',
    authDomain: 'petcare-plus-bcck2.firebaseapp.com',
    storageBucket: 'petcare-plus-bcck2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWJX6Vy9BzKhQ2h_W2M2BsKEUKp-4xBKU',
    appId: '1:1068366057685:android:aa7bc4d3f90489770ed25c',
    messagingSenderId: '1068366057685',
    projectId: 'app-petshop-27497',
    storageBucket: 'app-petshop-27497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjYgQI6Va4noRCRGeLBB2N11D1qoCK-k',
    appId: '1:705600051401:ios:080bac9423e6f3ade1d518',
    messagingSenderId: '705600051401',
    projectId: 'petcare-plus-bcck2',
    storageBucket: 'petcare-plus-bcck2.firebasestorage.app',
    iosBundleId: 'com.example.petcarePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjYgQI6Va4noRCRGeLBB2N11D1qoCK-k',
    appId: '1:705600051401:ios:080bac9423e6f3ade1d518',
    messagingSenderId: '705600051401',
    projectId: 'petcare-plus-bcck2',
    storageBucket: 'petcare-plus-bcck2.firebasestorage.app',
    iosBundleId: 'com.example.petcarePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCeam7VItri3p4laOVqT0_LtoOFhz7W4',
    appId: '1:705600051401:web:3eb57c97e7676c00e1d518',
    messagingSenderId: '705600051401',
    projectId: 'petcare-plus-bcck2',
    authDomain: 'petcare-plus-bcck2.firebaseapp.com',
    storageBucket: 'petcare-plus-bcck2.firebasestorage.app',
  );
}